# Copyright (c) 2025-2026 EDGEMTech SA

# Display main platform - NOTE: this doesn't handle overrides...
show_platform() {
	IB_PLATFORM=$(grep "^IB_PLATFORM.*" build/conf/local.conf | sed -n '1p' | grep -o \".*\")
	echo "Configured for platform = ${IB_PLATFORM}"
}

# Print the active infrabase environment to stderr. Sourced by the
# top-level scripts (build.sh, deploy.sh) and the bitbake wrapper so
# the active project is always visible at invocation time. Also warns
# when cwd lives inside a different infrabase project than the one
# whose env.sh is currently loaded.
#
# Optional arguments: recipe name, then task name. When provided, they
# are shown right after the "[infrabase]" tag so the user sees which
# recipe and task the active env will be applied to.

show_env() {
	_recipe="$1"
	_task="$2"
	_tag='[infrabase]'
	if test -n "$_recipe"; then
		_tag="$_tag $_recipe"
	fi
	if test -n "$_task"; then
		_tag="$_tag -c $_task"
	fi

	_platform=
	if test -n "$BUILDDIR" && test -r "$BUILDDIR/conf/local.conf"; then
		_platform=$(grep "^IB_PLATFORM" "$BUILDDIR/conf/local.conf" \
			| head -1 | sed -n 's/.*"\([^"]*\)".*/\1/p')
	fi

	printf '%s  root=%s  platform=%s\n' \
		"$_tag" "${IB_ROOT_DIR:-<unset>}" "${_platform:-<unknown>}" >&2

	# Walk up from cwd looking for an env.sh; if it belongs to a
	# different project than IB_ROOT_DIR, that's almost certainly a
	# user mistake — flag it.

	_candidate=$(readlink -f "$PWD" 2>/dev/null || pwd)
	while test "$_candidate" != "/" && ! test -f "$_candidate/env.sh"; do
		_candidate=$(dirname "$_candidate")
	done
	if test -f "$_candidate/env.sh" && test -n "$IB_ROOT_DIR"; then
		_active=$(readlink -f "$IB_ROOT_DIR" 2>/dev/null || echo "$IB_ROOT_DIR")
		if test "$_candidate" != "$_active"; then
			printf '%s  WARNING: cwd is inside %s but loaded env is %s\n' \
				"$_tag" "$_candidate" "$_active" >&2
			printf '%s           Re-source %s/env.sh if that was unintended.\n' \
				"$_tag" "$_candidate" >&2
		fi
	fi
}


# Regenerate build/conf/bblayers.conf with the full set of so3 layers.
#
# The file is rewritten in-place ONLY when its content would change — this
# keeps `git status` quiet for back-to-back invocations.

regen_bblayers() {
	_path="$BUILDDIR/conf/bblayers.conf"

	_tmp=$(mktemp)
	{
		echo "# Auto-generated by scripts/build.sh —"
		echo "# scripts/common/bblayers.sh:regen_bblayers(). Hand edits will be"
		echo "# overwritten on the next build.sh invocation."
		echo ""
		echo 'BBPATH := "${TOPDIR}"'
		echo 'BBFILES ?= ""'
		echo 'BBLAYERS = " \'
		for _l in meta meta-qemu meta-filesystem meta-uboot meta-linux \
		          meta-rootfs meta-usr meta-bsp meta-so3 meta-atf \
		          meta-toolchain; do
			echo "  \${TOPDIR}/$_l \\"
		done
		echo '  "'
	} > "$_tmp"

	if ! cmp -s "$_tmp" "$_path" 2>/dev/null; then
		mv "$_tmp" "$_path"
		printf '[infrabase] bblayers.conf regenerated\n' >&2
	else
		rm -f "$_tmp"
	fi
}

# Determine the amount of first lines to
# throw away from the output generated by bitbake-layers

bblayers_header_end_lineno() {
	echo $1 | grep -n "=== Available recipes: ===" | awk -F':' '{print $1}'
}

available_recipes() {
	layernames="$1"

	if test -z "$layernames"
	then
		# No layernames specified, print all recipes
		IFS=$(printf '\n')
		res=$(bitbake-layers show-recipes -b -r 2>/dev/null)
		headerloc=$(bblayers_header_end_lineno $res)
		echo $res | sed "1,${headerloc}d"
	else
		# layernames specified, print recipes from specified layers
		all=''
		for l in $layernames
		do
			IFS=$(printf '\n')
			res=$(bitbake-layers show-recipes -b -l "$l" -r 2>/dev/null)

			headerloc=$(bblayers_header_end_lineno $res)
			res=$(echo $res | sed "1,${headerloc}d")

			if test -z $all
			then
				all="$res"
			else
				all=$(printf "$all\n$res")
			fi
		done
		echo $all
	fi

}
