# Copyright (c) 2025-2026 EDGEMTech SA

# Display main platform - NOTE: this doesn't handle overrides...
show_platform() {
	IB_PLATFORM=$(grep "^IB_PLATFORM.*" build/conf/local.conf | sed -n '1p' | grep -o \".*\")
	echo "Configured for platform = ${IB_PLATFORM}"
}

# Print the active infrabase environment to stderr. Sourced by the
# top-level scripts (build.sh, deploy.sh) and the bitbake wrapper so
# the active project is always visible at invocation time. Also warns
# when cwd lives inside a different infrabase project than the one
# whose env.sh is currently loaded.
#
# Optional arguments: recipe name, then task name. When provided, they
# are shown right after the "[infrabase]" tag so the user sees which
# recipe and task the active env will be applied to.

show_env() {
	_recipe="$1"
	_task="$2"
	_tag='[infrabase]'
	if test -n "$_recipe"; then
		_tag="$_tag $_recipe"
	fi
	if test -n "$_task"; then
		_tag="$_tag -c $_task"
	fi

	_platform=
	if test -n "$BUILDDIR" && test -r "$BUILDDIR/conf/local.conf"; then
		# Report the EFFECTIVE platform. bitbake uses last-assignment-wins,
		# and an image build may append "IB_PLATFORM = ..." after the
		# "IB_PLATFORM ?= ..." default (e.g. the lv_perf Dockerfiles), so
		# take the last plain (non-override) assignment, not the first.
		_platform=$(grep -E "^IB_PLATFORM[[:space:]]*[?:]?=" "$BUILDDIR/conf/local.conf" \
			| grep -v "^IB_PLATFORM:" \
			| tail -1 | sed -n 's/.*"\([^"]*\)".*/\1/p')
	fi

	printf '%s  root=%s  platform=%s\n' \
		"$_tag" "${IB_ROOT_DIR:-<unset>}" "${_platform:-<unknown>}" >&2

	# Walk up from cwd looking for an env.sh; if it belongs to a
	# different project than IB_ROOT_DIR, that's almost certainly a
	# user mistake — flag it.

	_candidate=$(readlink -f "$PWD" 2>/dev/null || pwd)
	while test "$_candidate" != "/" && ! test -f "$_candidate/env.sh"; do
		_candidate=$(dirname "$_candidate")
	done
	if test -f "$_candidate/env.sh" && test -n "$IB_ROOT_DIR"; then
		_active=$(readlink -f "$IB_ROOT_DIR" 2>/dev/null || echo "$IB_ROOT_DIR")
		if test "$_candidate" != "$_active"; then
			printf '%s  WARNING: cwd is inside %s but loaded env is %s\n' \
				"$_tag" "$_candidate" "$_active" >&2
			printf '%s           Re-source %s/env.sh if that was unintended.\n' \
				"$_tag" "$_candidate" >&2
		fi
	fi
}


# Regenerate build/conf/bblayers.conf.
#
# Emits the generic layer set — Linux + ATF/OP-TEE + SO3/AVZ + U-Boot + QEMU
# + rootfs/usr/bsp — then whatever layers the product declares in
# IB_PRODUCT_LAYERS (env.sh), then, if one was requested, a single overlay
# layer given as a path relative to TOPDIR.
#
# meta-so3 is the canonical home of the AVZ recipe in every tree of this
# family, so it keeps that name here even though Infrabase carries only its
# avz half; the SO3 *kernel* recipe stays out. This base boots Linux,
# standalone or as an AVZ guest, and a product adds the rest.
#
# The overlay is deliberately anonymous here. Infrabase has no business
# knowing what a product layers on top, or why; it only knows that a tree may
# want one extra layer active for a build, and that the choice has to persist
# between build.sh and deploy.sh. A product that overlays product variants, a
# customer skin, or nothing at all uses the same mechanism.
#
# The generic layer set is unconditional: which of atf/optee/avz a given
# build actually compiles is decided by the stages in IB_BOOT_CHAIN at the
# dependency level (bsp.bbclass), not by adding and removing layers.
#
# The file is rewritten in-place ONLY when its content would change — this
# keeps `git status` quiet for back-to-back invocations of the same overlay.

regen_bblayers() {
	_overlay="$1"
	_path="$BUILDDIR/conf/bblayers.conf"

	_tmp=$(mktemp)
	{
		echo "# Auto-generated by scripts/build.sh — layer selection lives in"
		echo "# scripts/common/bblayers.sh:regen_bblayers(). Hand edits will be"
		echo "# overwritten on the next build.sh invocation."
		echo "# Active overlay: ${_overlay:-<none>}"
		echo ""
		echo 'BBPATH := "${TOPDIR}"'
		echo 'BBFILES ?= ""'
		echo 'BBLAYERS = " \'
		for _l in meta meta-qemu meta-filesystem meta-uboot meta-linux \
		          meta-rootfs meta-usr meta-bsp meta-atf meta-so3 \
		          meta-toolchain $IB_PRODUCT_LAYERS; do
			echo "  \${TOPDIR}/$_l \\"
		done
		if test -n "$_overlay"; then
			echo "  \${TOPDIR}/${_overlay} \\"
		fi
		echo '  "'
	} > "$_tmp"

	if ! cmp -s "$_tmp" "$_path" 2>/dev/null; then
		mv "$_tmp" "$_path"
		printf '[infrabase] bblayers.conf regenerated (overlay=%s)\n' \
			"${_overlay:-<none>}" >&2
	else
		rm -f "$_tmp"
	fi
}


# Echo the overlay layer path currently wired into build/conf/bblayers.conf,
# read back from the "# Active overlay:" header regen_bblayers() writes there.
#
# Echoes nothing when no overlay is active, when the header is absent
# (hand-written file), or on a fresh tree where the file does not exist
# yet — all three mean "no overlay", which is exactly what regen_bblayers()
# expects from an empty argument.

active_overlay_layer() {
	_aol_path="$BUILDDIR/conf/bblayers.conf"

	test -f "$_aol_path" || return 0

	_aol_overlay=$(sed -n 's/^# Active overlay:[[:space:]]*\(.*\)$/\1/p' \
		"$_aol_path" | head -1)

	if test -n "$_aol_overlay" && test "$_aol_overlay" != "<none>"; then
		printf '%s' "$_aol_overlay"
	fi
}


# Map a recipe back to the overlay layer that provides it, by scanning
# $IB_OVERLAY_DIR for a layer shipping a "<recipe>_*.bb". Echoes the layer
# path relative to TOPDIR, or nothing.
#
# A filesystem lookup rather than a naming rule: infrabase stays free of any
# convention about how a product names its overlays, and a product adding a
# new overlay needs no change here.

overlay_layer_for_recipe() {
	test -n "$1" || return 0
	test -n "$IB_OVERLAY_DIR" || return 0
	test -d "$BUILDDIR/$IB_OVERLAY_DIR" || return 0

	for _olr_dir in "$BUILDDIR/$IB_OVERLAY_DIR"/*/; do
		test -d "$_olr_dir" || continue
		for _olr_bb in "$_olr_dir"recipes-*/*/"$1"_*.bb; do
			test -f "$_olr_bb" || continue
			printf '%s/%s' "$IB_OVERLAY_DIR" \
				"$(basename "${_olr_dir%/}")"
			return 0
		done
	done
}


# Load an overlay layer's declaration into the environment, so the build
# scripts can honour it before bitbake ever starts.
#
# An overlay may ship conf/overlay.conf declaring:
#   IB_OVERLAY_BOOT_CHAIN   boot chain it requires (see regen_boot_chain)
#   IB_OVERLAY_RECIPES      base recipes it can be layered onto
#
# Both are optional and both are always reset first, so a stale value from
# a previously-read overlay can never leak into this one.

read_overlay_decl() {
	IB_OVERLAY_BOOT_CHAIN=""
	IB_OVERLAY_RECIPES=""

	test -n "$1" || return 0
	test -f "$BUILDDIR/$1/conf/overlay.conf" || return 0

	. "$BUILDDIR/$1/conf/overlay.conf"
}


# Select the overlay layer to activate, then settle the boot chain.
# Centralised so build.sh and deploy.sh share the same heuristic — otherwise
# each script could pick a different overlay for the same invocation.
#
# Two inputs:
#   $1 = explicit overlay layer path, relative to TOPDIR. Wins when set;
#        the recipe name is then ignored.
#   $2 = recipe name. Used only when $1 is empty, and then it splits three
#        ways:
#          provided by an overlay  the recipe IS an overlay's own — activate
#                                  the layer providing it.
#          bsp-*                   a bare BSP build — no overlay, so the
#                                  engineer can iterate on the BSP alone.
#          *                       a component (avz, uboot, linux, …) —
#                                  carries no overlay context of its own, so
#                                  preserve whatever overlay is already
#                                  active.
#
# That last case matters: regen_boot_chain() preserves the in-effect
# IB_BOOT_CHAIN for components, and the overlay layer is the other half of
# that same mode. Dropping it while the chain stays put leaves the overlay's
# own variables unset, and the next deploy then ships a layout the overlay's
# artefacts are missing from — silently, with the boot failing as the first
# symptom.

regen_bblayers_for_recipe() {
	_rbfr_overlay="$1"
	_rbfr_recipe="$2"

	if test -z "$_rbfr_overlay"; then
		_rbfr_overlay=$(overlay_layer_for_recipe "$_rbfr_recipe")
	fi
	if test -z "$_rbfr_overlay"; then
		case "$_rbfr_recipe" in
			bsp-*)	;;
			*)	_rbfr_overlay=$(active_overlay_layer) ;;
		esac
	fi

	# Snapshot before calling regen_bblayers — that function clobbers
	# the global $_overlay (no `local` in POSIX sh).
	_rbfr_keep="$_rbfr_overlay"
	regen_bblayers "$_rbfr_overlay"

	# Propagate a rejected IB_BOOT_CHAIN_REQUEST: the caller (build.sh /
	# deploy.sh) must stop rather than build with a stale auto.conf.

	regen_boot_chain "$_rbfr_keep" "$_rbfr_recipe" || return 1
}


# Regenerate ${BUILDDIR}/conf/auto.conf with a global IB_BOOT_CHAIN value.
#
# Needed because the uboot recipe's OVERRIDES does NOT contain :linux — so
# an `IB_BOOT_CHAIN:linux:virt64` in local.conf is invisible in that scope.
# auto.conf is loaded by bitbake right after local.conf and an unscoped
# assignment there wins for every recipe, uboot included.
#
# WHO DECIDES THE CHAIN depends on whether the tree has overlays:
#
#   no IB_OVERLAY_DIR (infrabase as shipped)
#       local.conf decides, as it always has. auto.conf is written only to
#       honour an explicit IB_BOOT_CHAIN_REQUEST, and is otherwise emptied
#       so it cannot override the value the user set by hand. Anything else
#       would make `IB_BOOT_CHAIN = "atf+uboot"` in local.conf silently
#       ineffective, which is the opposite of what this file is for.
#
#   IB_OVERLAY_DIR set (a product tree)
#       the chain is DERIVED from (overlay, recipe, platform): an active
#       overlay declares it in conf/overlay.conf, and a bare BSP build falls
#       back to a platform-appropriate default. A component recipe carries no
#       chain context of its own and inherits whatever is already in effect.
#
# IB_BOOT_CHAIN_REQUEST wins in both cases. It is read HERE, by the script,
# rather than by bitbake, so that the value reaches recipes as the unscoped
# auto.conf assignment and the uboot scope sees the same chain as bsp-*.

regen_boot_chain() {
	_rbc_overlay="$1"
	_recipe="$2"
	_path="$BUILDDIR/conf/auto.conf"

	# When called directly rather than through regen_bblayers_for_recipe,
	# resolve the overlay from the recipe so both entry points agree.
	if test -z "$_rbc_overlay"; then
		_rbc_overlay=$(overlay_layer_for_recipe "$_recipe")
	fi

	read_overlay_decl "$_rbc_overlay"

	# Effective platform = last plain (non-override) IB_PLATFORM assignment
	# (image builds may append one after the ?= default).
	_platform=$(grep -E "^IB_PLATFORM[[:space:]]*[?:]?=" "$BUILDDIR/conf/local.conf" \
		| grep -v "^IB_PLATFORM:" \
		| tail -1 | sed -n 's/.*"\([^"]*\)".*/\1/p')

	# An explicit request wins over anything derived. This is the supported
	# way to ask for a chain the (overlay, recipe, platform) triple does not
	# produce on its own — notably "atf+optee+uboot", a bare build WITH a
	# secure world.

	_requested=$(grep -E "^IB_BOOT_CHAIN_REQUEST[[:space:]]*[?:]?=" \
		"$BUILDDIR/conf/local.conf" 2>/dev/null \
		| tail -1 | sed -n 's/.*"\([^"]*\)".*/\1/p')

	if [ -n "$_requested" ]; then
		# Token check only. The chain is an ordered list of stages
		# (atf+optee+uboot+avz+mcuboot); the order, the requirements
		# between stages and what a platform supports are all checked
		# by base.bbclass:ib_normalize_boot_axes, which is the one
		# place that sees the whole picture. Here we only catch a
		# typo before writing it to auto.conf.
		if test "$_requested" != "full"; then
			for _stage in $(printf '%s\n' "$_requested" | tr '+' ' '); do
				case "$_stage" in
					atf|optee|uboot|avz|mcuboot) ;;
					*)
						printf '[infrabase] ERROR: IB_BOOT_CHAIN_REQUEST="%s": unknown stage "%s"\n' \
							"$_requested" "$_stage" >&2
						printf '[infrabase]        stages, in boot order: atf optee uboot avz mcuboot\n' >&2
						printf '[infrabase]        e.g. "uboot", "atf+optee+uboot+avz", "uboot+mcuboot"\n' >&2
						return 1
						;;
				esac
			done
		fi
		_chain="$_requested"
		printf '[infrabase] auto.conf forced by IB_BOOT_CHAIN_REQUEST=%s (local.conf)\n' \
			"$_chain" >&2
		__write_auto_conf "$_path" "$_chain"
		return 0
	fi

	# No overlays in this tree: local.conf is in charge. Leave auto.conf
	# without an IB_BOOT_CHAIN so it cannot override what the user set.
	if test -z "$IB_OVERLAY_DIR"; then
		__write_auto_conf "$_path" ""
		return 0
	fi

	# A recipe resolves to a chain when it is a BSP, or when it belongs to
	# an overlay (it then carries that overlay's declared chain). Component
	# recipes (uboot, linux, atf, ...) do not: clobbering auto.conf with an
	# empty IB_BOOT_CHAIN there breaks the next bitbake task that reads it.

	if test -n "$(overlay_layer_for_recipe "$_recipe")"; then
		_rbc_resolves=1
	else
		case "$_recipe" in
			bsp-*)	_rbc_resolves=1 ;;
			*)	_rbc_resolves=0 ;;
		esac
	fi

	if test "$_rbc_resolves" = "0"; then
		# Component builds inherit the mode in effect, and fall back to
		# a platform-appropriate default on a fresh tree.
		if [ -f "$_path" ] && grep -q "^IB_BOOT_CHAIN" "$_path"; then
			_existing=$(grep "^IB_BOOT_CHAIN" "$_path" \
				| sed -n 's/.*"\([^"]*\)".*/\1/p')
			printf '[infrabase] auto.conf preserved (recipe %s inherits IB_BOOT_CHAIN=%s)\n' \
				"${_recipe:-<none>}" "$_existing" >&2
			return 0
		fi
		case "$_platform" in
			verdin-imx8mp) _chain="atf+uboot" ;;
			*)             _chain="uboot" ;;
		esac
		printf '[infrabase] auto.conf regenerated (recipe %s, no prior chain — defaulting to IB_BOOT_CHAIN=%s for platform %s)\n' \
			"${_recipe:-<none>}" "$_chain" "$_platform" >&2
		__write_auto_conf "$_path" "$_chain"
		return 0
	fi

	# Overlay -> base-recipe compatibility. An overlay usually gates its own
	# variables on the BSP class it targets, so pairing it with a
	# non-matching bsp recipe silently produces none of its artefacts — and
	# then adopting its boot chain drives deploy down a path whose inputs
	# were never built. Detect the mismatch and treat it as "no overlay".
	#
	# Declared by the overlay in IB_OVERLAY_RECIPES; an overlay that leaves
	# it empty claims compatibility with every base recipe.

	_overlay_compatible=1
	if test -n "$_rbc_overlay" && test -n "$IB_OVERLAY_RECIPES"; then
		case "$_recipe" in
			bsp-*)
				_overlay_compatible=0
				for _rbc_ok in $IB_OVERLAY_RECIPES; do
					if test "$_rbc_ok" = "$_recipe"; then
						_overlay_compatible=1
					fi
				done
				if test "$_overlay_compatible" = "0"; then
					printf '[infrabase] WARNING: overlay "%s" declares IB_OVERLAY_RECIPES="%s" — not compatible with %s, falling back to bare boot chain\n' \
						"$_rbc_overlay" "$IB_OVERLAY_RECIPES" \
						"$_recipe" >&2
				fi
				;;
		esac
	fi

	if [ -n "$_rbc_overlay" ] && [ "$_overlay_compatible" = "1" ] \
	   && [ -n "$IB_OVERLAY_BOOT_CHAIN" ]; then
		_chain="$IB_OVERLAY_BOOT_CHAIN"
	else
		case "$_platform" in
			verdin-imx8mp) _chain="atf+uboot" ;;
			*)             _chain="uboot" ;;
		esac
	fi

	__write_auto_conf "$_path" "$_chain"
}


# Write auto.conf, rewriting it only when its content would change so a
# back-to-back invocation stays quiet. An empty chain writes the header
# alone, which is how "local.conf is in charge" is expressed.

__write_auto_conf() {
	_wac_path="$1"
	_wac_chain="$2"

	_tmp=$(mktemp)
	{
		echo "# Auto-generated by scripts/common/bblayers.sh:regen_boot_chain."
		echo "# Loaded automatically by bitbake after local.conf. Hand"
		echo "# edits will be overwritten on the next build.sh / deploy.sh"
		echo "# invocation."
		if [ -n "$_wac_chain" ]; then
			echo "IB_BOOT_CHAIN = \"$_wac_chain\""
		fi
	} > "$_tmp"

	if ! cmp -s "$_tmp" "$_wac_path" 2>/dev/null; then
		mv "$_tmp" "$_wac_path"
		printf '[infrabase] auto.conf regenerated (IB_BOOT_CHAIN=%s)\n' \
			"${_wac_chain:-<unset, local.conf decides>}" >&2
	else
		rm -f "$_tmp"
	fi
}

# Determine the amount of first lines to
# throw away from the output generated by bitbake-layers

bblayers_header_end_lineno() {
	echo $1 | grep -n "=== Available recipes: ===" | awk -F':' '{print $1}'
}

available_recipes() {
	layernames="$1"

	if test -z "$layernames"
	then
		# No layernames specified, print all recipes
		IFS=$(printf '\n')
		res=$(bitbake-layers show-recipes -b -r 2>/dev/null)
		headerloc=$(bblayers_header_end_lineno $res)
		echo $res | sed "1,${headerloc}d"
	else
		# layernames specified, print recipes from specified layers
		all=''
		for l in $layernames
		do
			IFS=$(printf '\n')
			res=$(bitbake-layers show-recipes -b -l "$l" -r 2>/dev/null)

			headerloc=$(bblayers_header_end_lineno $res)
			res=$(echo $res | sed "1,${headerloc}d")

			if test -z $all
			then
				all="$res"
			else
				all=$(printf "$all\n$res")
			fi
		done
		echo $all
	fi

}
