
# Display main platform - NOTE: this doesn't handle overrides...
show_platform() {
	IB_PLATFORM=$(grep "^IB_PLATFORM.*" build/conf/local.conf | sed -n '1p' | grep -o \".*\")
	echo "Configured for platform = ${IB_PLATFORM}"
}


# Determine the amount of first lines to
# throw away from the output generated by bitbake-layers
bblayers_header_end_lineno() {
	echo $1 | grep -n "=== Available recipes: ===" | awk -F':' '{print $1}'
}

available_recipes() {
	layernames="$1"

	if test -z "$layernames"
	then
		# No layernames specified, print all recipes
		IFS=$(printf '\n')
		res=$(bitbake-layers show-recipes -b -r 2>/dev/null)
		headerloc=$(bblayers_header_end_lineno $res)
		echo $res | sed "1,${headerloc}d"
	else
		# layernames specified, print recipes from specified layers
		all=''
		for l in $layernames
		do
			IFS=$(printf '\n')
			res=$(bitbake-layers show-recipes -b -l "$l" -r 2>/dev/null)

			headerloc=$(bblayers_header_end_lineno $res)
			res=$(echo $res | sed "1,${headerloc}d")

			if test -z $all
			then
				all="$res"
			else
				all=$(printf "$all\n$res")
			fi
		done
		echo $all
	fi

}
