# Automatically generated by configure - do not modify
TARGET_PPC=y
TARGET_NAME=ppc
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/rossierd/src/qemu/gdb-xml/power-core.xml /home/rossierd/src/qemu/gdb-xml/power-fpu.xml /home/rossierd/src/qemu/gdb-xml/power-altivec.xml /home/rossierd/src/qemu/gdb-xml/power-spe.xml
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
