#!/bin/bash

# Copyright (C) 2025 Clément Dieperink <clement.dieperink@heig-vd.ch>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
#
# This script generates two header for syscall number and table based on two
# inputs files.
#
# The input files are:
#
#  - syscall.tbl: Declares all syscalls available on SO3 without taking into
#                 account the CPU arch. This also provides configuration
#                 requirement for a given syscall.
#                 Requirement can be set to EMPTY_IMPLEMENTATION, which will
#                 set a default function returning -ENOSYS for syscalls that
#                 are intentionally not implemented.
#  - syscall.h.in: Contains all syscall number which are necessary implemented
#                  in SO3. This is a copy of the same file from musl library.
#
# Output files are:
#
#  - syscall_number.h: Defines all available on arch SYSCALL_xxx with
#                      corresponding number and dependent on the configuration.
#  - syscall_table.h.in: Table definition with elements of array definition to
#                        match syscall number to syscall functions. This file
#                        must be included inside a C table definition.

set -e

usage() {
	echo >&2 "usage: $0 in_table in_number out_table out_number" >&2
	echo >&2
	echo >&2 "  in_table   input syscall table common for all arch"
	echo >&2 "  in_number  input syscall number arch dependent"
	echo >&2 "  out_table  output syscall callback table"
	echo >&2 "  out_number output syscall number conditional"
	exit 1
}

file_header() {
	echo "#ifndef $1"
	echo "#define $1"
	echo "/*"
	echo " * DO NOT MODIFY."
	echo " *"
	echo " * This file was generated by $(realpath "$0")"
	echo " */"
	echo ""
}

file_footer() {
	echo ""
	echo "#endif"
}

if [ $# -ne 4 ]; then
	usage
fi

infile_table="$1"
infile_number="$2"
outfile_table="$3"
outfile_number="$4"

declare -Ag sys_cond=()

# Generate syscall_table.h.in file and save available syscall
# and there configuration requirement.
file_header "__SYSCALL_TABLE_H__" > "$outfile_table"

valid_syscalls="$(grep -E "^[^#]" "$infile_table")"
while read name requirement; do
	sys_cond["$name"]="$requirement"

	echo "#ifdef SYSCALL_$name"
	if [ "$requirement" = "EMPTY_IMPLEMENTATION" ]; then
		echo -e "\t[SYSCALL_$name] = &__sys_empty,"
	else
		echo -e "\t[SYSCALL_$name] = &__sys_$name,"
	fi
	echo "#endif"
done < <(echo "$valid_syscalls") >> "$outfile_table"

file_footer >> "$outfile_table"

# Generate syscall_number.h
grep -E "^#define " "$infile_number" | sed "s/^#define __NR_//" | {
	file_header "__SYSCALL_NUMBER_H__"
	echo "#include <generated/autoconf.h>"
	echo ""

	while read name number; do
		if ! [ -v sys_cond[$name] ]; then
			continue
		fi

		if [ -n "${sys_cond[$name]}" -a "${sys_cond[$name]}" != "EMPTY_IMPLEMENTATION" ]; then
			echo "#ifdef CONFIG_${sys_cond[$name]}"
		fi

		echo "#define SYSCALL_$name $number"

		if [ -n "${sys_cond[$name]}" -a "${sys_cond[$name]}" != "EMPTY_IMPLEMENTATION" ]; then
			echo "#endif"
		fi
	done

	file_footer
} > "$outfile_number"
