obj-$(CONFIG_SOO_SWITCH_KNX) += switch.o callbacks.o gtl2tw.o
obj-$(CONFIG_SOO_SWITCH_ENOCEAN) += switch.o callbacks.o enocean.o ptm210.o

# obj-y += switch.o callbacks.o enocean.o pt210.o gtl2tw.o

# ifeq $()