
add_executable(init.elf init.c)
add_executable(sh.elf sh.c)
add_executable(ls.elf ls.c)
add_executable(cat.elf cat.c)
add_executable(touch.elf touch.c)
add_executable(mkdir.elf mkdir.c)
add_executable(rmdir.elf rmdir.c)
add_executable(rm.elf rm.c)
add_executable(mv.elf mv.c)
add_executable(cp.elf cp.c)
add_executable(more.elf more.c)
add_executable(time.elf time.c)
add_executable(thread_example.elf thread_example.c)
add_executable(ping.elf ping.c)
add_executable(mydev_test.elf mydev_test.c)
add_executable(fb_test.elf fb_test.c)
add_executable(logs_example.elf logs_example.c)

target_link_libraries(logs_example.elf capsule_logs)

if (MICROPYTHON AND (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "aarch64"))
	message("== Building uPython")
	add_subdirectory(micropython)
endif()

option(WITH_TESTS "Build the test/example apps" ON)
if (WITH_TESTS)
    add_subdirectory(tests)
endif()

