obj-y += api_lib.o
obj-y += api_msg.o
obj-y += err.o
obj-y += if_api.o
obj-y += netbuf.o
obj-y += netdb.o
obj-y += netifapi.o
obj-y += sockets.o
obj-y += tcpip.o

EXTRA_CFLAGS += -I$(srctree)/include/net
