obj-y += vdevfront.o

obj-$(CONFIG_VDUMMY_FRONTEND) += vdummyfront/
obj-$(CONFIG_VUART_FRONTEND) += vuartfront/
obj-$(CONFIG_VUIHANDLER_FRONTEND) += vuihandlerfront/
obj-$(CONFIG_VSENSELED_FRONTEND) += vsenseledfront/
obj-$(CONFIG_VSENSEJ_FRONTEND) += vsensejfront/
