obj-y += 	main.o
obj-y += spinlock.o
obj-y += mutex.o
obj-y += schedule.o
obj-y += timer.o
obj-y += softirq.o
obj-y += thread.o
obj-y += syscalls.o
obj-y += delay.o
obj-y += eabi_compat.o
obj-y += calibrate.o

		
 obj-$(CONFIG_MMU) += process.o ptrace.o

