
# Object file lists.

obj-y	+= console.o

obj-y += agency_build.o 

obj-${CONFIG_SOO} += ME_build.o

obj-y += domain.o
obj-y += setup.o
obj-y += event_channel.o
obj-y += keyhandler.o
obj-y += timer.o
obj-y += sched_flip.o 
obj-y += schedule.o
obj-y += hypercalls.o
obj-${CONFIG_SOO} += gnttab.o

obj-y += image-fit.o
obj-y += domain_utils.o

obj-${CONFIG_SOO} += injector.o




