obj-y = device.o irq.o timer.o network.o

obj-$(CONFIG_UART) += serial.o

obj-$(CONFIG_MMC) += mmc/
obj-$(CONFIG_UART) += serial/

obj-$(CONFIG_RAMDEV) += ramdev/

obj-$(CONFIG_NET) += network/

obj-y += timer/
obj-y += irq/
