obj-y += ipv4/
obj-y += ipv6/

obj-y += altcp.o
obj-y += altcp_alloc.o
obj-y += altcp_tcp.o
obj-y += def.o
obj-y += dns.o
obj-y += inet_chksum.o
obj-y += init.o
obj-y += ip.o
obj-y += mem.o
obj-y += memp.o
obj-y += netif.o
obj-y += pbuf.o
obj-y += raw.o
obj-y += stats.o
obj-y += sys.o
obj-y += tcp.o
obj-y += tcp_in.o
obj-y += tcp_out.o
obj-y += timeouts.o
obj-y += udp.o

EXTRA_CFLAGS += -I$(srctree)/include/net
