
obj-y += bridgeif.o
obj-y += bridgeif_fdb.o
obj-y += ethernet.o
obj-y += lowpan6.o
obj-y += lowpan6_ble.o
obj-y += lowpan6_common.o
#obj-y += slipif.o
obj-y += zepif.o

EXTRA_CFLAGS += -I$(srctree)/include/net
