
obj-y += head.o
obj-y += setup.o exception.o context.o fault.o
obj-y += cache_v7_asm.o cache_v7.o cache-cp15.o
obj-y += thread.o
obj-y += vfp.o
obj-y += backtrace.o backtrace_asm.o
obj-y += smccc-call.o
obj-y += syscalls.o
obj-y += kuser_helper.o

obj-y += lib/

obj-$(CONFIG_MMU) += mmu.o

obj-y += $(TARGET)/

