# Automatically generated by configure - do not modify
TARGET_AARCH64=y
TARGET_NAME=aarch64
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=aarch64
CONFIG_SOFTMMU=y
TARGET_SUPPORTS_MTTCG=y
TARGET_XML_FILES= /home/rossierd/src/qemu/gdb-xml/aarch64-core.xml /home/rossierd/src/qemu/gdb-xml/aarch64-fpu.xml /home/rossierd/src/qemu/gdb-xml/arm-core.xml /home/rossierd/src/qemu/gdb-xml/arm-vfp.xml /home/rossierd/src/qemu/gdb-xml/arm-vfp3.xml /home/rossierd/src/qemu/gdb-xml/arm-neon.xml
CROSS_CC_GUEST="aarch64-linux-gnu-gcc"
CROSS_CC_GUEST_STATIC=y
CONFIG_I386_DIS=y
CONFIG_ARM_DIS=y
CONFIG_ARM_A64_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
