
obj-y += common.o

obj-$(CONFIG_SOO_REFSO3) += refso3/
obj-$(CONFIG_SOO_OUTDOOR) += outdoor/
obj-$(CONFIG_SOO_BLIND) += blind/
obj-$(CONFIG_SOO_AGENCY) += agency/
obj-$(CONFIG_SOO_NET) += net/
obj-$(CONFIG_SOO_LEDCTRL) += ledctrl/
obj-$(CONFIG_SOO_CHAT) += chat/
obj-$(CONFIG_SOO_WAGOLED) += wagoled/
obj-$(CONFIG_SOO_SWITCH_ENOCEAN) += switch/
obj-$(CONFIG_SOO_SWITCH_KNX) += switch/




