pipeline {
    agent any

    // TODO : Setup for multiple platforms

    stages {
        stage('Setup toolchain') {
            steps {
                sh "./ci/pipeline_steps/setup_toolchain.sh"
            }
        }
        stage('Build QEMU') {
            steps {
                sh "./ci/pipeline_steps/build_qemu.sh"
            }
        }
        stage('Build U-Boot') {
            steps {
                sh "./ci/pipeline_steps/build_uboot.sh"
            }
        }
        stage('Build SO3') {
            steps {
                sh "./ci/pipeline_steps/build_so3.sh"
            }
        }
        stage('Build User Space') {
            steps {
                sh "./ci/pipeline_steps/build_usr.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "./ci/pipeline_steps/deploy.sh"
            }
        }
        stage('Boot SO3') {
            steps {
                timeout(time: 1, unit: 'MINUTES') {
                    sh "./ci/pipeline_steps/boot_so3.sh"
                }
            }
        }
        stage('Launch Tests') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    sh "./ci/pipeline_steps/launch_tests.sh"
                    junit 'ci/*.xml'
                }
            }
        }
    }
}