# Automatically generated by configure - do not modify
TARGET_PPC64=y
TARGET_NAME=ppc64le
TARGET_BASE_ARCH=ppc
TARGET_ABI_DIR=ppc
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-ppc64le"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/rossierd/src/qemu/gdb-xml/power64-core.xml /home/rossierd/src/qemu/gdb-xml/power-fpu.xml /home/rossierd/src/qemu/gdb-xml/power-altivec.xml /home/rossierd/src/qemu/gdb-xml/power-spe.xml /home/rossierd/src/qemu/gdb-xml/power-vsx.xml
CONFIG_I386_DIS=y
CONFIG_PPC_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
