
# Object file lists.

obj-y	+= console.o

obj-y += agency_build.o ME_build.o
obj-y += domain.o
obj-y += physdev.o
obj-y += setup.o
obj-y += event_channel.o
obj-y += keyhandler.o
obj-y += timer.o
obj-y += sched_flip.o 
obj-y += schedule.o
obj-y += migration.o
obj-y += domctl.o
obj-y += soo_activity.o

obj-y += image-fit.o
obj-y += domain_utils.o
obj-y += injector.o
obj-y += logbool.o



